[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "yarobot"
requires-python = ">=3.12"
description = "Yara generator inspired by yarGen"
dependencies = [
    "lief>=0.13.0",
    "lxml>=4.9.0",
    "orjson>=3.11", 
]
version = "0.1.1"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = [
  "-vv",				        # подробный вывод хода теста
  "--import-mode=importlib"  	# меньше проблем с импортами
]
pythonpath = ["."]