[project]
name = "yarobot"
version = "0.2.1" 
authors = [
  { name="ogre2007", email="oogre@vk.com" },
]

requires-python = ">=3.10"
description = "YARA generator inspired by yarGen"
readme = "README.md"
license = { text = "GPL-3.0-only" }
dependencies = [
    "flask>=3.1.2",
        "click>=8.3.0",
    "lxml>=4.9.0",
    "orjson>=3.11",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project.scripts]
yarobot = "yarobot.generate:generate" 

[project.urls]
Homepage = "https://github.com/ogre2007/yarobot"
Issues = "https://github.com/ogre2007/issues"

[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]
module-name = "yarobot.yarobot_rs"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = [
  "-vv",				       
  "--import-mode=importlib"
]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "lxml>=4.9.0",
    "pytest-datadir>=1.8.0",
    "yara-python>=4.5.4",
    "orjson>=3.11",
    "click>=8.3.0",
]
